apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: life-app
type: Opaque
stringData:
  # TODO: Add POSTGRES_USER
  POSTGRES_USER: life
  # TODO: Add POSTGRES_PASSWORD
  POSTGRES_PASSWORD: life2026
